# versão do docker-compose
version: "3.7"

# inicio da orquestração
services:
  # nome do serviço
  app:

    # comando de buildar o docker usando os arquivos q estão no path atual
    build: .

    # nome do container
    container_name: rentx

    # mapeando a porta do container com a do pc 
    ports: 
      - 3333:3333   

    # seria o workdir do cntainer, . é a pasta atual : é pra onde os arquivos vão dentro do container
    volumes:
      - .:/usr/app 


## Para executar o docker-compose:
  ## docker-compose up -d
  ## flag -d serve para ele rodar em background

## Para acompanhar o container:
  ## docker logs "nome do container" -f